### PR TITLE
LPS-83163 App Manager is unusable after installing an app

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-83163](https://issues.liferay.com/browse/LPS-83163).<br><br>Hey @lionah, this fixes the issue as described in the ticket, but I wanted you to look at this because I am not sure it is necessarily the only fix needed.  My main question is: should there ever be a case where an app display is created with no bundles?  If not, should we just prevent the app display from being added to the list in the first place?  Let me know what you think.<br><br>/cc @pei-jung @jeffreyyang @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by lionah** [comment]
Thanks! https://github.com/brianchandotcom/liferay-portal/pull/61310

I'm a little weird out that bundles can be empty. What does this look like when it reaches the front end?

**Comment by lionah** [comment]
Just saw you top comment. Yes I also find it pretty odd that there are cases where there are no bundles. When you were testing what did you find where there were 0 bundles?

**Comment by drewbrokke** [comment]
I found it because of the Array index exception, but I haven't yet pinpointed the cause of the bundles array not being populated.  It only happened with the implementation of `MarketplaceAppDisplay`, not `SimpleAppDisplay`.  I'd imagine it happens in `AppDisplayFactoryUtil::createMarketplaceAppDisplay`.  Either `_moduleLocalService.getModules(app.getAppId())` returns an empty list or `bundlesMap.getBundle(module)` returns a null value.

**Comment by lionah** [comment]
Oh.. In this case, it might be correct. The original App Manager had the ability to see something that was previously installed was no longer installed. It might be what is going on here.

**Pull request closed without merging**
