### PR TITLE
Lps 78803

### PR DESCRIPTION
**Pull request by mtambara**
Here are most of the new subsystem.bnd files. Apio-architect isn't included because it's a subrepo, so either I can send it and you can add the metadata after it gets merged, or you can send it to them with the metadata. Static will be in a separate pull because it requires code changes

cc @shuyangzhou

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:lpkg

**Comment by shuyangzhou** [comment]
@lionah any update on this? Do we have an ETA for it.

**Comment by lionah** [comment]
@shuyangzhou sorry, last time I looked at this I thought it was in Brian's queue.

**Comment by lionah** [comment]
Oddly.. it is already merged on Fri Mar 16 14:50:43 2018 -0700.

**Pull request closed without merging**
