### PR TITLE
LPS-77699 | master

### PR DESCRIPTION
**Pull request by jpince**

### CODE REVIEW

**Comment by jpince** [comment]
@lionah not sure why there's a merge conflict, I don't get this when cherry-picking to my local master branch.

Can you please review the Auto SF changes at head (ran `ant format-source-all '-Dskip.npm=true'), and investigate why these were not required when you sent the translations update?
cc/ @jhendley @petershin

**Comment by lionah** [comment]
@jpince They look fine. I updated the branch with SF but I think Brian merged it before the changes were up.

**Comment by jpince** [comment]
@lionah can you please resend or forward to Brian?

**Comment by lionah** [comment]
Yep, I was in the middle of that. https://github.com/brianchandotcom/liferay-portal/pull/64399

**Comment by jpince** [comment]
thanks @lionah

**Pull request closed without merging**
